name: Mark RFC proposals

on:
  pull_request:
    types: [ready_for_review]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mark-rfc-proposals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: https://github.com/jonmeow/test/projects/1
          column: RFC
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: RFC
