name: Comment when opened
on:
  pull_request:
    types:
      - labeled

jobs:
  updateLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - if: github.event.label.name == 'proposal: rfc'
        run: |
          gh pr edit "${PR}"
          --add-label "proposal"
          --remove-label "proposal: accepted"
          --remove-label "proposal: deferred"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}

      - if: github.event.label.name == "proposal: accepted"
        run: |
          gh pr edit "${PR}"
          --add-label "proposal"
          --remove-label "proposal: rfc"
          --remove-label "proposal: deferred"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}

      - if: github.event.label.name == "proposal: deferred"
        run: |
          gh pr edit "${PR}"
          --add-label "proposal"
          --remove-label "proposal: rfc"
          --remove-label "proposal: accepted"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
