name: Comment when opened
on:
  pull_request:
    types:
      - labeled

jobs:
  updateLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: rfc
        if: |
          github.event.label.name == 'proposal rfc'
        run: |
          gh pr edit "${PR}" \
            --remove-label "proposal accepted" \
            --remove-label "proposal deferred" \
            --add-label "proposal"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}

      - name: accepted
        if: |
          github.event.label.name == 'proposal accepted'
        run: |
          gh pr edit "${PR}" \
            --remove-label "proposal rfc" \
            --remove-label "proposal deferred" \
            --add-label "proposal"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}

      - name: deferred
        if: |
          github.event.label.name == 'proposal deferred'
        run: |
          gh pr edit "${PR}" \
            --remove-label "proposal rfc" \
            --remove-label "proposal accepted" \
            --add-label "proposal"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
