name: Comment when opened
on:
  pull_request:
    types:
      - ready_for_review

jobs:
  proposalRfc:
    if: contains(github.event.pull_request.labels.*.name, 'proposal')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: rfc
        run: |
          gh pr edit "${PR}" \
            --remove-label "proposal accepted" \
            --remove-label "proposal deferred" \
            --add-label "proposal"
            --add-label "proposal rfc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
