name: Respond to ready for review

on:
  pull_request:
    types: [labeled]

jobs:
  update-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: Update project column
        uses: jonmeow/action-update-project@main
        with:
          project_url: https://github.com/jonmeow/test/projects/1
          column_name: RFC
          github_token: ${{ secrets.GITHUB_TOKEN }}
