name: Comment when opened
on:
  pull_request:
    types:
      - ready_for_review

jobs:
  updateLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: rfc
        run: |
          echo 1
          #gh pr edit "${PR}" \
          #  --remove-label "proposal accepted" \
          #  --remove-label "proposal deferred" \
          #  --add-label "proposal"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
